const express = require('express');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const LEVELS = require('./levels.js');
const app = express();
const PORT = process.env.PORT || 3000;
const DATA_DIR = path.join(__dirname, 'data');
const DB_FILE = path.join(DATA_DIR, 'db.json');
app.use((req,res,next)=>{ res.header('Access-Control-Allow-Origin','*'); res.header('Access-Control-Allow-Headers','Content-Type, Authorization'); res.header('Access-Control-Allow-Methods','GET,POST,PUT,DELETE,OPTIONS'); if(req.method==='OPTIONS') return res.sendStatus(204); next(); });
app.use(express.json({ limit: '6mb' }));
app.use(express.static(path.join(__dirname, 'public')));
const DATABASE_URL = process.env.DATABASE_URL;
let USE_PG = !!DATABASE_URL;
let pool = null;
if (USE_PG) {
  try { const { Pool } = require('pg'); pool = new Pool({ connectionString: DATABASE_URL, ssl: DATABASE_URL.includes('localhost') ? false : { rejectUnauthorized: false } }); console.log('📦 Usando PostgreSQL persistente'); } catch(e) { console.log('⚠️ pg no instalado, usando archivo JSON. Instala con npm i pg'); USE_PG = false; }
}
if (!USE_PG) console.log('📁 Usando archivo JSON local (efímero en Render free sin Postgres)');
function defaultDb(){ return { users: [], sessions: [], notifications: [], tournaments: [], chat: [], friendships: [], privateMessages: [] }; }
function loadDb(){ if(!fs.existsSync(DB_FILE)) return defaultDb(); try{ const d=JSON.parse(fs.readFileSync(DB_FILE,'utf8')); if(!d.friendships) d.friendships=[]; if(!d.privateMessages) d.privateMessages=[]; if(!d.chat) d.chat=[]; return d; }catch(e){ return defaultDb(); } }
function saveDb(db){ if(!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR,{recursive:true}); fs.writeFileSync(DB_FILE, JSON.stringify(db,null,2)); }
let fileDb = loadDb();
if(!fileDb.tournaments) fileDb.tournaments=[];
if(!fileDb.chat) fileDb.chat=[];
if(!fileDb.notifications) fileDb.notifications=[];
if(!fileDb.sessions) fileDb.sessions=[];
if(!fileDb.users) fileDb.users=[];
if(!fileDb.friendships) fileDb.friendships=[];
if(!fileDb.privateMessages) fileDb.privateMessages=[];
async function initPg(){
  if(!USE_PG) return;
  try{
    await pool.query(`CREATE TABLE IF NOT EXISTS users (
      id TEXT PRIMARY KEY, username TEXT UNIQUE NOT NULL, salt TEXT NOT NULL, password_hash TEXT NOT NULL,
      progress TEXT NOT NULL DEFAULT '[]', coins INT NOT NULL DEFAULT 0, skins TEXT NOT NULL DEFAULT '["default"]',
      equipped TEXT NOT NULL DEFAULT 'default', profile_pic TEXT NOT NULL DEFAULT '', theme TEXT NOT NULL DEFAULT 'dark',
      hours_played INT NOT NULL DEFAULT 0, exp INT NOT NULL DEFAULT 0, frames TEXT NOT NULL DEFAULT '["none"]',
      equipped_frame TEXT NOT NULL DEFAULT 'none', speedrun_best INT, speedrun_history TEXT NOT NULL DEFAULT '[]',
      created_at TEXT NOT NULL, last_seen TEXT, name_color TEXT NOT NULL DEFAULT '#ffffff', owned_name_colors TEXT NOT NULL DEFAULT '[]', chat_bg TEXT NOT NULL DEFAULT '', banners TEXT NOT NULL DEFAULT '["none"]', equipped_banner TEXT NOT NULL DEFAULT 'none', banner_img TEXT NOT NULL DEFAULT '', fonts TEXT NOT NULL DEFAULT '["normal"]', equipped_font TEXT NOT NULL DEFAULT 'normal', fxs TEXT NOT NULL DEFAULT '["none"]', equipped_fx TEXT NOT NULL DEFAULT 'none'
    )`);
    await pool.query(`CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE)`);
    await pool.query(`CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, title TEXT NOT NULL, body TEXT NOT NULL, type TEXT NOT NULL, read BOOLEAN NOT NULL DEFAULT false, created_at TEXT NOT NULL)`);
    await pool.query(`CREATE TABLE IF NOT EXISTS tournaments (id TEXT PRIMARY KEY, status TEXT NOT NULL, start_date TEXT NOT NULL, end_date TEXT NOT NULL, results TEXT NOT NULL DEFAULT '{}')`);
    await pool.query(`CREATE TABLE IF NOT EXISTS chat_messages (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, username TEXT NOT NULL, text TEXT NOT NULL, created_at TEXT NOT NULL)`);
    await pool.query(`CREATE TABLE IF NOT EXISTS friendships (id TEXT PRIMARY KEY, requester_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, addressee_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, status TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(requester_id, addressee_id))`);
    await pool.query(`CREATE TABLE IF NOT EXISTS private_messages (id TEXT PRIMARY KEY, sender_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, receiver_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, text TEXT NOT NULL, created_at TEXT NOT NULL)`);
    await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS last_seen TEXT`);
    await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS name_color TEXT NOT NULL DEFAULT '#ffffff'`);
    await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS owned_name_colors TEXT NOT NULL DEFAULT '[]'`);
    await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS chat_bg TEXT NOT NULL DEFAULT ''`);
    await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS banners TEXT NOT NULL DEFAULT '["none"]'`);
    await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS equipped_banner TEXT NOT NULL DEFAULT 'none'`);
    await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS banner_img TEXT NOT NULL DEFAULT ''`);
    await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS fonts TEXT NOT NULL DEFAULT '["normal"]'`);
    await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS equipped_font TEXT NOT NULL DEFAULT 'normal'`);
    await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS fxs TEXT NOT NULL DEFAULT '["none"]'`);
    await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS equipped_fx TEXT NOT NULL DEFAULT 'none'`);
    console.log('✅ Tablas PG listas');
    const r = await pool.query('SELECT COUNT(*) FROM users');
    if(parseInt(r.rows[0].count)===0 && fileDb.users.length>0){
      for(const u of fileDb.users){ await pgUpsertUser(u); }
      for(const s of fileDb.sessions){ try{ await pool.query('INSERT INTO sessions(token,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[s.token,s.userId]); }catch(e){} }
      for(const n of fileDb.notifications){ try{ await pool.query('INSERT INTO notifications(id,user_id,title,body,type,read,created_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT DO NOTHING',[n.id,n.userId,n.title,n.body,n.type,n.read,n.createdAt]); }catch(e){} }
      for(const t of fileDb.tournaments){ try{ await pool.query('INSERT INTO tournaments(id,status,start_date,end_date,results) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING',[t.id,t.status,t.startDate,t.endDate,JSON.stringify(t.results||{})]); }catch(e){} }
    }
  }catch(e){ console.error('PG init error',e.message); USE_PG=false; }
}
function ensureShopFields(u){
  if(u.coins===undefined) u.coins=0;
  if(!u.skins) u.skins=['default'];
  if(!u.equipped) u.equipped='default';
  if(!u.skins.includes('default')) u.skins.unshift('default');
  if(u.profilePic===undefined) u.profilePic='';
  if(!u.theme) u.theme='dark';
  if(u.hoursPlayed===undefined) u.hoursPlayed=0;
  if(u.exp===undefined) u.exp=0;
  if(!u.frames) u.frames=[];
  if(!u.equippedFrame) u.equippedFrame='none';
  if(!u.frames.includes('none')) u.frames.unshift('none');
  if(u.speedrunBest===undefined) u.speedrunBest=null;
  if(!u.speedrunHistory) u.speedrunHistory=[];
  if(!u.lastSeen) u.lastSeen=null;
  if(!u.nameColor) u.nameColor='#ffffff';
  if(!u.ownedNameColors) u.ownedNameColors=[];
  if(u.chatBg===undefined) u.chatBg='';
  if(!u.banners) u.banners=['none'];
  if(!u.equippedBanner) u.equippedBanner='none';
  if(!u.banners.includes('none')) u.banners.unshift('none');
  if(u.bannerImg===undefined) u.bannerImg='';
  if(!u.fonts) u.fonts=['normal'];
  if(!u.equippedFont) u.equippedFont='normal';
  if(!u.fxs) u.fxs=['none'];
  if(!u.equippedFx) u.equippedFx='none';
  if(!u.fxs.includes('none')) u.fxs.unshift('none');
  if(!u.fonts.includes('normal')) u.fonts.unshift('normal');
}
fileDb.users.forEach(ensureShopFields);
if(!USE_PG) saveDb(fileDb);
function pgRowToUser(r){
  return { id:r.id, username:r.username, salt:r.salt, passwordHash:r.password_hash, progress: JSON.parse(r.progress||'[]'), coins:r.coins, skins: JSON.parse(r.skins||'["default"]'), equipped:r.equipped, profilePic:r.profile_pic||'', theme:r.theme||'dark', hoursPlayed:r.hours_played||0, exp:r.exp||0, frames: JSON.parse(r.frames||'["none"]'), equippedFrame:r.equipped_frame||'none', speedrunBest:r.speedrun_best, speedrunHistory: JSON.parse(r.speedrun_history||'[]'), createdAt:r.created_at, lastSeen:r.last_seen||null, nameColor:r.name_color||'#ffffff', ownedNameColors: JSON.parse(r.owned_name_colors||'[]'), chatBg:r.chat_bg||'', banners: JSON.parse(r.banners||'["none"]'), equippedBanner:r.equipped_banner||'none', bannerImg:r.banner_img||'', fonts: JSON.parse(r.fonts||'["normal"]'), equippedFont:r.equipped_font||'normal', fxs: JSON.parse(r.fxs||'["none"]'), equippedFx:r.equipped_fx||'none' };
}
async function pgUpsertUser(u){
  ensureShopFields(u);
  await pool.query(`INSERT INTO users(id,username,salt,password_hash,progress,coins,skins,equipped,profile_pic,theme,hours_played,exp,frames,equipped_frame,speedrun_best,speedrun_history,created_at,last_seen,name_color,owned_name_colors,chat_bg,banners,equipped_banner,banner_img,fonts,equipped_font,fxs,equipped_fx)
  VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28)
  ON CONFLICT(id) DO UPDATE SET username=EXCLUDED.username, salt=EXCLUDED.salt, password_hash=EXCLUDED.password_hash, progress=EXCLUDED.progress, coins=EXCLUDED.coins, skins=EXCLUDED.skins, equipped=EXCLUDED.equipped, profile_pic=EXCLUDED.profile_pic, theme=EXCLUDED.theme, hours_played=EXCLUDED.hours_played, exp=EXCLUDED.exp, frames=EXCLUDED.frames, equipped_frame=EXCLUDED.equipped_frame, speedrun_best=EXCLUDED.speedrun_best, speedrun_history=EXCLUDED.speedrun_history, last_seen=EXCLUDED.last_seen, name_color=EXCLUDED.name_color, owned_name_colors=EXCLUDED.owned_name_colors, chat_bg=EXCLUDED.chat_bg, banners=EXCLUDED.banners, equipped_banner=EXCLUDED.equipped_banner, banner_img=EXCLUDED.banner_img, fonts=EXCLUDED.fonts, equipped_font=EXCLUDED.equipped_font, fxs=EXCLUDED.fxs, equipped_fx=EXCLUDED.equipped_fx`,
  [u.id,u.username,u.salt,u.passwordHash,JSON.stringify(u.progress||[]),u.coins||0,JSON.stringify(u.skins||['default']),u.equipped||'default',u.profilePic||'',u.theme||'dark',u.hoursPlayed||0,u.exp||0,JSON.stringify(u.frames||['none']),u.equippedFrame||'none',u.speedrunBest,JSON.stringify(u.speedrunHistory||[]),u.createdAt,u.lastSeen||null,u.nameColor||'#ffffff',JSON.stringify(u.ownedNameColors||[]),u.chatBg||'',JSON.stringify(u.banners||['none']),u.equippedBanner||'none',u.bannerImg||'',JSON.stringify(u.fonts||['normal']),u.equippedFont||'normal',JSON.stringify(u.fxs||['none']),u.equippedFx||'none']);
}
async function getAllUsers(){ if(USE_PG){ const r=await pool.query('SELECT * FROM users'); return r.rows.map(pgRowToUser); } return fileDb.users; }
async function getUserById(id){ if(USE_PG){ const r=await pool.query('SELECT * FROM users WHERE id=$1',[id]); return r.rows[0]?pgRowToUser(r.rows[0]):null; } return fileDb.users.find(u=>u.id===id)||null; }
async function getUserByUsername(username){ if(USE_PG){ const r=await pool.query('SELECT * FROM users WHERE username=$1',[username]); return r.rows[0]?pgRowToUser(r.rows[0]):null; } return fileDb.users.find(u=>u.username===username)||null; }
async function createUser(u){ if(USE_PG) await pgUpsertUser(u); else { fileDb.users.push(u); saveDb(fileDb); } }
async function updateUser(u){ if(USE_PG) await pgUpsertUser(u); else saveDb(fileDb); }
async function deleteUser(id){
  if(USE_PG){ await pool.query('DELETE FROM friendships WHERE requester_id=$1 OR addressee_id=$1',[id]); await pool.query('DELETE FROM private_messages WHERE sender_id=$1 OR receiver_id=$1',[id]); await pool.query('DELETE FROM users WHERE id=$1',[id]); }
  else { fileDb.users=fileDb.users.filter(u=>u.id!==id); fileDb.sessions=fileDb.sessions.filter(s=>s.userId!==id); fileDb.notifications=fileDb.notifications.filter(n=>n.userId!==id); fileDb.friendships=fileDb.friendships.filter(f=>f.requesterId!==id&&f.addresseeId!==id); fileDb.privateMessages=fileDb.privateMessages.filter(m=>m.senderId!==id&&m.receiverId!==id); saveDb(fileDb); }
}
async function findSession(token){ if(USE_PG){ const r=await pool.query('SELECT * FROM sessions WHERE token=$1',[token]); return r.rows[0]?{token:r.rows[0].token,userId:r.rows[0].user_id}:null; } return fileDb.sessions.find(s=>s.token===token)||null; }
async function createSession(token,userId){ if(USE_PG) await pool.query('INSERT INTO sessions(token,user_id) VALUES($1,$2)',[token,userId]); else { fileDb.sessions.push({token,userId}); saveDb(fileDb); } }
async function deleteSession(token){ if(USE_PG) await pool.query('DELETE FROM sessions WHERE token=$1',[token]); else { fileDb.sessions=fileDb.sessions.filter(s=>s.token!==token); saveDb(fileDb); } }
async function deleteSessionsByUser(userId){ if(USE_PG) await pool.query('DELETE FROM sessions WHERE user_id=$1',[userId]); else { fileDb.sessions=fileDb.sessions.filter(s=>s.userId!==userId); saveDb(fileDb); } }
async function getNotifications(userId){ if(USE_PG){ const r=await pool.query('SELECT * FROM notifications WHERE user_id=$1 ORDER BY created_at DESC',[userId]); return r.rows.map(x=>({id:x.id,userId:x.user_id,title:x.title,body:x.body,type:x.type,read:x.read,createdAt:x.created_at})); } return fileDb.notifications.filter(n=>n.userId===userId).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)); }
async function pushNotification(userId,title,body,type){ const n={id:crypto.randomUUID(),userId,title,body,type,read:false,createdAt:new Date().toISOString()}; if(USE_PG) await pool.query('INSERT INTO notifications(id,user_id,title,body,type,read,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[n.id,n.userId,n.title,n.body,n.type,n.read,n.createdAt]); else { fileDb.notifications.push(n); saveDb(fileDb); } }
async function markNotifications(userId,id){ if(USE_PG){ if(id) await pool.query('UPDATE notifications SET read=true WHERE user_id=$1 AND id=$2',[userId,id]); else await pool.query('UPDATE notifications SET read=true WHERE user_id=$1',[userId]); } else { fileDb.notifications.forEach(n=>{ if(n.userId===userId && (!id||n.id===id)) n.read=true; }); saveDb(fileDb); } }
async function getTournaments(){ if(USE_PG){ const r=await pool.query('SELECT * FROM tournaments'); return r.rows.map(x=>({id:x.id,status:x.status,startDate:x.start_date,endDate:x.end_date,results:JSON.parse(x.results||'{}')})); } return fileDb.tournaments; }
async function createTournament(t){ if(USE_PG) await pool.query('INSERT INTO tournaments(id,status,start_date,end_date,results) VALUES($1,$2,$3,$4,$5)',[t.id,t.status,t.startDate,t.endDate,JSON.stringify(t.results||{})]); else { fileDb.tournaments.push(t); saveDb(fileDb); } }
async function updateTournament(t){ if(USE_PG) await pool.query('UPDATE tournaments SET status=$1, results=$2 WHERE id=$3',[t.status,JSON.stringify(t.results||{}),t.id]); else saveDb(fileDb); }
async function getChat(limit=100){ let msgs; if(USE_PG){ const r=await pool.query('SELECT * FROM chat_messages ORDER BY created_at DESC LIMIT $1',[limit]); msgs=r.rows.map(x=>({id:x.id,userId:x.user_id,username:x.username,text:x.text,createdAt:x.created_at})).reverse(); } else msgs=(fileDb.chat||[]).slice(-limit); try{ const users=await getAllUsers(); const map=new Map(users.map(u=>[u.id,u])); msgs=msgs.map(m=>{ const u=map.get(m.userId); return Object.assign({},m,{nameColor:u?(u.nameColor||'#ffffff'):'#ffffff',equippedFont:u?(u.equippedFont||'normal'):'normal',equippedFx:u?(u.equippedFx||'none'):'none',profilePic:u?(u.profilePic||''):'',equippedFrame:u?(u.equippedFrame||'none'):'none'}); }); }catch(e){} return msgs; }
async function addChat(msg){ if(USE_PG) await pool.query('INSERT INTO chat_messages(id,user_id,username,text,created_at) VALUES($1,$2,$3,$4,$5)',[msg.id,msg.userId,msg.username,msg.text,msg.createdAt]); else { fileDb.chat.push(msg); if(fileDb.chat.length>500) fileDb.chat=fileDb.chat.slice(-500); saveDb(fileDb); } }
async function deleteChatByUser(userId){ if(USE_PG) await pool.query('DELETE FROM chat_messages WHERE user_id=$1',[userId]); else { fileDb.chat=(fileDb.chat||[]).filter(c=>c.userId!==userId); saveDb(fileDb); } }
function hashPassword(password,salt){ return crypto.scryptSync(password,salt,64).toString('hex'); }
function createToken(){ return crypto.randomBytes(32).toString('hex'); }
async function findUserByToken(req){ const token=(req.headers.authorization||'').replace('Bearer ',''); if(!token) return null; const session=await findSession(token); if(!session) return null; return await getUserById(session.userId); }
const SKINS=[ { id:'default', name:'DEV Cyan', price:0, body:'#00e5ff', glow:'#00e5ff' }, { id:'crimson', name:'Crimson Fury', price:120, body:'#ff1744', glow:'#ff5252' }, { id:'gold', name:'Golden Nova', price:200, body:'#ffd600', glow:'#ffea00' }, { id:'neon', name:'Neon Viper', price:300, body:'#00e676', glow:'#69f0ae' }, { id:'violet', name:'Violet Storm', price:350, body:'#7c4dff', glow:'#b388ff' }, { id:'pixel', name:'Pixel Phantom', price:500, body:'#ff6d00', glow:'#ff9e00' },{ id:'ocean', name:'Oceano', price:600, body:'#2196f3', glow:'#82b4ff' },{ id:'rosa', name:'Rosa Neon', price:750, body:'#ff4081', glow:'#ff8a80' },{ id:'lima', name:'Lima Acida', price:850, body:'#c6ff00', glow:'#eaff8a' },{ id:'ghost', name:'Fantasma', price:950, body:'#eceff1', glow:'#ffffff' },{ id:'camo', name:'Camuflaje', price:1000, body:'#7c9a3f', glow:'#b2d67c' },{ id:'magma', name:'Magma', price:1200, body:'#ff3d00', glow:'#ff8a65' },{ id:'ice', name:'Hielo', price:1350, body:'#80d8ff', glow:'#e1f5fe' },{ id:'nebula', name:'Nebulosa', price:1500, body:'#e040fb', glow:'#ea80fc' },{ id:'solar', name:'Solar', price:1650, body:'#fff176', glow:'#ffd600' },{ id:'platinum', name:'Platino', price:1800, body:'#cfd8dc', glow:'#ffffff' },{ id:'obsidian', name:'Obsidiana', price:2100, body:'#1a1a2e', glow:'#ff1744' },{ id:'diamond', name:'Diamante', price:2500, body:'#b3ffff', glow:'#ffffff' }, { id:'tournament_silver', name:'🥈 Silver Ranked', price:0, body:'#c0c0c0', glow:'#e0e0e0', exclusive:true } ];
const FRAMES=[ { id:'none',    name:'Sin marco',       price:0 }, { id:'bronce',  name:'Marco Bronce',    price:200 }, { id:'plata',   name:'Marco Plata',     price:400 }, { id:'oro',     name:'Marco Oro',       price:700 }, { id:'neon',    name:'Marco Neón',      price:1000 }, { id:'diamante',name:'Marco Diamante',  price:1500 }, { id:'campeon', name:'🏆 Marco Campeón (Animado)', price:0, animated:true, exclusive:true }, { id:'inferno', name:'🔥 Marco Inferno (GIF)', price:20000, animated:true }, { id:'galaxy', name:'🌌 Marco Galaxia (GIF)', price:25000, animated:true }, { id:'glitch', name:'👾 Marco Glitch (GIF)', price:30000, animated:true }, { id:'void', name:'🕳️ Marco Vacío (GIF)', price:35000, animated:true }, { id:'dragon', name:'🐉 Marco Dragón (Épico)', price:50000, animated:true }, { id:'leyenda', name:'💎 Marco Leyenda (TRYHARD)', price:75000, animated:true } ];
const NAME_COLORS=[ {id:'white',name:'Blanco',color:'#ffffff',price:3000},{id:'cyan',name:'Cyan',color:'#00e5ff',price:3000},{id:'gold',name:'Dorado',color:'#ffd600',price:3500},{id:'pink',name:'Rosa',color:'#ff4081',price:3000},{id:'green',name:'Verde',color:'#00e676',price:3000},{id:'violet',name:'Violeta',color:'#7c4dff',price:3500},{id:'red',name:'Rojo',color:'#ff1744',price:4000},{id:'rainbow',name:'🌈 Arcoíris',color:'rainbow',price:5000} ];
const BANNERS=[ {id:'none',name:'Sin banner',price:0,grad:'transparent',border:'#333'},{id:'bronce',name:'Bronce',price:300,grad:'linear-gradient(135deg,#6b3a1f,#cd7f32)',border:'#cd7f32'},{id:'plata',name:'Plata',price:600,grad:'linear-gradient(135deg,#6e7a80,#c0c0c0)',border:'#c0c0c0'},{id:'negro',name:'Negro',price:400,grad:'linear-gradient(135deg,#000000,#2a2a2e)',border:'#666'},{id:'blanco',name:'Blanco',price:400,grad:'linear-gradient(135deg,#cfd4da,#ffffff)',border:'#ffffff'},{id:'rojo',name:'Rojo',price:800,grad:'linear-gradient(135deg,#7a0e1e,#ff1744)',border:'#ff5252'},{id:'azul',name:'Azul',price:800,grad:'linear-gradient(135deg,#0d2a6b,#2979ff)',border:'#448aff'},{id:'verde',name:'Verde',price:800,grad:'linear-gradient(135deg,#0d4d1f,#00e676)',border:'#00e676'},{id:'rosa',name:'Rosa',price:1000,grad:'linear-gradient(135deg,#8a1c5c,#ff4081)',border:'#ff80ab'},{id:'celeste',name:'Celeste',price:1000,grad:'linear-gradient(135deg,#0d4d6b,#00e5ff)',border:'#00e5ff'},{id:'platino',name:'Platino',price:1200,grad:'linear-gradient(135deg,#3a4a5a,#40c4ff)',border:'#40c4ff'},{id:'dorado',name:'Dorado',price:2000,grad:'linear-gradient(135deg,#7a5a00,#ffd600)',border:'#ffd600'},{id:'oro_puro',name:'Oro Puro',price:3500,grad:'linear-gradient(135deg,#ff8c00,#ffe082,#ff8c00)',border:'#ffe082'},{id:'leyenda',name:'Leyenda Animado',price:5000,grad:'linear-gradient(90deg,#ff1744,#ffd600,#00e676,#00e5ff,#7c4dff)',border:'#fff',animated:true} ];
const FONTS=[ {id:'normal',name:'Normal',price:0,css:''}, {id:'titan',name:'Titan',price:3000,css:'font-weight:900;font-family:Impact,sans-serif;letter-spacing:1px;'}, {id:'mono',name:'Hacker Mono',price:3000,css:'font-family:monospace;font-weight:700;'}, {id:'cursiva',name:'Cursiva',price:3500,css:'font-style:italic;font-weight:700;font-family:cursive;letter-spacing:1px;'}, {id:'redonda',name:'Redondeada',price:4000,css:'font-family:Trebuchet MS,Verdana,sans-serif;font-weight:800;'}, {id:'elegante',name:'Elegante',price:4500,css:'font-family:Georgia,serif;font-style:italic;letter-spacing:1px;'}, {id:'gotica',name:'Gotica',price:5000,css:'font-family:Georgia,serif;font-weight:700;text-transform:uppercase;letter-spacing:3px;'}, {id:'minecraft',name:'Minecraft',price:6000,css:'font-family:monospace;font-weight:900;text-transform:uppercase;letter-spacing:2px;text-shadow:2px 2px 0 rgba(0,0,0,.65);'}, {id:'cuadrada',name:'Cuadrada',price:7000,css:'font-family:Verdana,sans-serif;font-weight:900;text-transform:uppercase;letter-spacing:1px;text-shadow:1px 1px 0 rgba(0,0,0,.6);'}, {id:'pixel',name:'Pixel',price:8000,css:'font-family:monospace;font-weight:900;text-transform:uppercase;letter-spacing:4px;text-shadow:0 0 8px currentColor;'}, {id:'sombra',name:'Sombra Neon',price:10000,css:'font-weight:900;letter-spacing:1px;text-shadow:0 0 10px currentColor,0 0 22px currentColor;'}, {id:'latido',name:'Latido',price:12000,css:'font-weight:900;display:inline-block;animation:fxBeat 1.2s ease-in-out infinite;'}, {id:'ola',name:'Ola',price:14000,css:'font-weight:800;display:inline-block;animation:fxWave 1.8s ease-in-out infinite;'}, {id:'neonvivo',name:'Neon Vivo',price:15000,css:'font-weight:900;animation:fxNeon 1.6s ease-in-out infinite;'}, {id:'fuego',name:'Fuego',price:18000,css:'font-weight:900;text-transform:uppercase;background:linear-gradient(180deg,#ffe082,#ff8c00,#ff1744);-webkit-background-clip:text;background-clip:text;color:transparent;animation:fxFire 1.1s ease-in-out infinite;'}, {id:'glitch',name:'Glitch',price:20000,css:'font-family:monospace;font-weight:900;text-transform:uppercase;animation:fxGlitch 1.4s steps(2,end) infinite;'}, {id:'arcoiris',name:'Arcoiris Vivo',price:25000,css:'font-weight:900;background:linear-gradient(90deg,#ff1744,#ffd600,#00e676,#00e5ff,#7c4dff,#ff1744);background-size:300% 100%;-webkit-background-clip:text;background-clip:text;color:transparent;animation:fxRainbow 3s linear infinite;'} ];
const FXS=[ {id:'none',name:'Sin efecto',price:0,css:''}, {id:'latido',name:'Latido',price:12000,css:'display:inline-block;animation:fxBeat 1.2s ease-in-out infinite;'}, {id:'ola',name:'Ola',price:14000,css:'display:inline-block;animation:fxWave 1.8s ease-in-out infinite;'}, {id:'neon',name:'Neon',price:15000,css:'animation:fxNeon 1.6s ease-in-out infinite;'}, {id:'brillo',name:'Brillo',price:16000,css:'font-weight:900;background:linear-gradient(100deg,#8a93a6 30%,#ffffff 50%,#8a93a6 70%);background-size:200% 100%;-webkit-background-clip:text;background-clip:text;color:transparent;animation:fxShine 2.4s linear infinite;'}, {id:'fuego',name:'Fuego',price:18000,css:'font-weight:900;text-transform:uppercase;background:linear-gradient(180deg,#ffe082,#ff8c00,#ff1744);-webkit-background-clip:text;background-clip:text;color:transparent;animation:fxFire 1.1s ease-in-out infinite;'}, {id:'glitch',name:'Glitch',price:20000,css:'animation:fxGlitch 1.4s steps(2,end) infinite;'}, {id:'arcoiris',name:'Arcoiris',price:25000,css:'font-weight:900;background:linear-gradient(90deg,#ff1744,#ffd600,#00e676,#00e5ff,#7c4dff,#ff1744);background-size:300% 100%;-webkit-background-clip:text;background-clip:text;color:transparent;animation:fxRainbow 3s linear infinite;'} ];


function levelFromExp(exp){ let lv=1,left=Number(exp)||0,need=100; while(left>=need){ left-=need; lv++; need=100+(lv-1)*50; } return {level:lv,into:left,need}; }
function formatSpeedrunMs(ms){ const s=ms/1000,m=Math.floor(s/60),sec=Math.floor(s%60),cs=Math.floor((ms%1000)/10); return String(m).padStart(2,'0')+':'+String(sec).padStart(2,'0')+'.'+String(cs).padStart(2,'0'); }
function publicUser(u){ return { id:u.id, username:u.username, createdAt:u.createdAt, coins:u.coins||0, skins:u.skins||['default'], equipped:u.equipped||'default', profilePic:u.profilePic||'', theme:u.theme||'dark', hoursPlayed: Math.floor((u.hoursPlayed||0)/3600), exp:u.exp||0, frames:u.frames||[], equippedFrame:u.equippedFrame||'none', speedrunBest:u.speedrunBest||null, nameColor:u.nameColor||'#ffffff', ownedNameColors:u.ownedNameColors||[], chatBg:u.chatBg||'', banners:u.banners||['none'], equippedBanner:u.equippedBanner||'none', bannerImg:u.bannerImg||'', fonts:u.fonts||['normal'], equippedFont:u.equippedFont||'normal', fxs:u.fxs||['none'], equippedFx:u.equippedFx||'none', lastSeen:u.lastSeen||null }; }
function isOnline(lastSeen){ if(!lastSeen) return false; return (Date.now()-new Date(lastSeen).getTime()) < 5*60*1000; }
app.get('/favicon.ico',(req,res)=>res.status(204).end());
app.post('/api/register', async (req,res)=>{ const {username,password}=req.body||{}; if(!username||!password) return res.status(400).json({error:'Usuario y contraseña son obligatorios'}); if(String(username).length<3) return res.status(400).json({error:'El usuario debe tener al menos 3 caracteres'}); if(String(password).length<4) return res.status(400).json({error:'La contraseña debe tener al menos 4 caracteres'}); if(await getUserByUsername(username)) return res.status(409).json({error:'Ese usuario ya existe'}); const salt=crypto.randomBytes(16).toString('hex'); const user={ id:crypto.randomUUID(), username, salt, passwordHash:hashPassword(password,salt), progress:[], coins:0, skins:['default'], equipped:'default', profilePic:'', theme:'dark', hoursPlayed:0, exp:0, frames:['none'], equippedFrame:'none', speedrunBest:null, speedrunHistory:[], createdAt:new Date().toISOString(), lastSeen:new Date().toISOString(), nameColor:'#ffffff', ownedNameColors:[], chatBg:'', banners:['none'], equippedBanner:'none', bannerImg:'', fonts:['normal'], equippedFont:'normal', fxs:['none'], equippedFx:'none' }; await createUser(user); const token=createToken(); await createSession(token,user.id); await pushNotification(user.id,'Bienvenido a Code Invaders 👾','¡Cuenta creada con éxito! Empieza a jugar en la sección Juego.','success'); res.status(201).json({token,user:publicUser(user)}); });
app.post('/api/login', async (req,res)=>{ const {username,password}=req.body||{}; const user=await getUserByUsername(username); if(!user || user.passwordHash!==hashPassword(password,user.salt)) return res.status(401).json({error:'Usuario o contraseña incorrectos'}); user.lastSeen=new Date().toISOString(); await updateUser(user); const token=createToken(); await createSession(token,user.id); await pushNotification(user.id,'Sesión iniciada ✅',`Hola ${user.username}, ¡buen regreso!`,'info'); res.json({token,user:publicUser(user)}); });
app.post('/api/logout', async (req,res)=>{ const token=(req.headers.authorization||'').replace('Bearer ',''); if(token) await deleteSession(token); res.json({ok:true}); });
app.get('/api/me', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); ensureShopFields(user); const lv=levelFromExp(user.exp); res.json({user:publicUser(user),progress:user.progress,coins:user.coins,skins:user.skins,equipped:user.equipped,expLevel:lv}); });
app.post('/api/heartbeat', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); user.lastSeen=new Date().toISOString(); await updateUser(user); res.json({ok:true, online:true}); });
app.get('/api/progress', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); res.json({progress:user.progress}); });
app.put('/api/progress', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); ensureShopFields(user); const {level,attempts,solved,coinsEarned}=req.body||{}; if(!level) return res.status(400).json({error:'Falta el nivel'}); let entry=user.progress.find(p=>p.level===level); if(!entry){ entry={level,attempts:0,solved:false,solvedAt:null}; user.progress.push(entry); } entry.attempts+=Number(attempts)||1; if(solved && !entry.solved){ entry.solved=true; entry.solvedAt=new Date().toISOString(); await pushNotification(user.id,'¡Nivel completado! 🎉',`Completaste el nivel ${level}. ¡Sigue así!`,'success'); } if(Number(coinsEarned)) user.coins+=Number(coinsEarned); await updateUser(user); res.json({progress:user.progress,coins:user.coins}); });
app.get('/api/leaderboard', async (req,res)=>{ res.set('Cache-Control','no-store'); const users=await getAllUsers(); const board=users.map(u=>({id:u.id,username:u.username,solved:u.progress.filter(p=>p.solved).length,attempts:u.progress.reduce((a,p)=>a+p.attempts,0),exp:u.exp||0,hoursPlayed:Math.floor((u.hoursPlayed||0)/3600),profilePic:u.profilePic||'',equippedFrame:u.equippedFrame||'none',coins:u.coins||0,nameColor:u.nameColor||'#ffffff',equippedFont:u.equippedFont||'normal',equippedFx:u.equippedFx||'none',online:isOnline(u.lastSeen)})).sort((a,b)=>b.solved-a.solved||b.exp-a.exp||a.attempts-b.attempts); res.json({board}); });
app.get('/api/leaderboard/speedrun', async (req,res)=>{ res.set('Cache-Control','no-store'); const users=await getAllUsers(); const board=users.filter(u=>u.speedrunBest!=null).map(u=>({id:u.id,username:u.username,speedrunBest:u.speedrunBest,solved:u.progress.filter(p=>p.solved).length,exp:u.exp||0,profilePic:u.profilePic||'',equippedFrame:u.equippedFrame||'none',coins:u.coins||0,nameColor:u.nameColor||'#ffffff',equippedFont:u.equippedFont||'normal',equippedFx:u.equippedFx||'none',online:isOnline(u.lastSeen)})).sort((a,b)=>a.speedrunBest-b.speedrunBest); res.json({board}); });
app.post('/api/speedrun', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado, inicia sesión'}); ensureShopFields(user); const {time}=req.body||{}; const t=Math.round(Number(time)); if(!Number.isFinite(t)||t<=0) return res.status(400).json({error:'Tiempo inválido'}); if(t<1000||t>600000) return res.status(400).json({error:'Tiempo fuera de rango (1s - 10m)'}); const isNewBest=user.speedrunBest==null||t<user.speedrunBest; if(isNewBest){ user.speedrunBest=t; user.speedrunHistory.push({time:t,at:new Date().toISOString()}); if(user.speedrunHistory.length>20) user.speedrunHistory=user.speedrunHistory.slice(-20); await updateUser(user); await pushNotification(user.id,'⚡ Nuevo récord Speedrun',`⏱ ${formatSpeedrunMs(t)} — ¡Nuevo mejor tiempo!`,'success'); console.log(`[speedrun] ${user.username} ${t}ms isNew=${isNewBest}`); } else { console.log(`[speedrun] ${user.username} ${t}ms no mejora (best ${user.speedrunBest})`); } res.json({speedrunBest:user.speedrunBest,isNewBest}); });
app.get('/api/user/:id', async (req,res)=>{ const user=await getUserById(req.params.id); if(!user) return res.status(404).json({error:'Usuario no encontrado'}); res.json({id:user.id,username:user.username,profilePic:user.profilePic||'',equippedFrame:user.equippedFrame||'none',exp:user.exp||0,hoursPlayed:Math.floor((user.hoursPlayed||0)/3600),coins:user.coins||0,solved:user.progress.filter(p=>p.solved).length,attempts:user.progress.reduce((a,p)=>a+p.attempts,0),createdAt:user.createdAt,speedrunBest:user.speedrunBest||null,nameColor:user.nameColor||'#ffffff',equippedBanner:user.equippedBanner||'none',bannerImg:user.bannerImg||'',equippedFont:user.equippedFont||'normal',equippedFx:user.equippedFx||'none',online:isOnline(user.lastSeen)}); });
app.get('/api/notifications', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); const list=await getNotifications(user.id); res.json({notifications:list,unread:list.filter(n=>!n.read).length}); });
app.post('/api/notifications/read', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); const {id}=req.body||{}; await markNotifications(user.id,id); res.json({ok:true}); });
app.get('/api/shop',(req,res)=>{ res.json({skins:SKINS}); });
app.post('/api/shop/buy', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); ensureShopFields(user); const {skinId}=req.body||{}; const skin=SKINS.find(s=>s.id===skinId); if(!skin) return res.status(404).json({error:'Skin no existe'}); if(user.skins.includes(skinId)) return res.status(400).json({error:'Ya tienes esta skin'}); if(user.coins<skin.price) return res.status(400).json({error:'Puntos insuficientes'}); user.coins-=skin.price; user.skins.push(skinId); await updateUser(user); await pushNotification(user.id,'¡Skin comprada! 🛒',`Desbloqueaste ${skin.name}`,'success'); res.json({coins:user.coins,skins:user.skins}); });
app.post('/api/shop/equip', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); ensureShopFields(user); const {skinId}=req.body||{}; if(!user.skins.includes(skinId)) return res.status(400).json({error:'No tienes esta skin'}); user.equipped=skinId; await updateUser(user); res.json({equipped:user.equipped}); });
app.delete('/api/account', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); const userId=user.id; await deleteUser(userId); await deleteSessionsByUser(userId); if(USE_PG) await pool.query('DELETE FROM notifications WHERE user_id=$1',[userId]); else { fileDb.notifications=fileDb.notifications.filter(n=>n.userId!==userId); saveDb(fileDb); } await deleteChatByUser(userId); const tours=await getTournaments(); for(const t of tours){ if(t.results && t.results[userId]){ delete t.results[userId]; await updateTournament(t); } } res.json({ok:true}); });
app.put('/api/settings', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); ensureShopFields(user); const {username,theme,profilePic,chatBg,bannerImg}=req.body||{}; if(username!==undefined){ const name=String(username).trim(); if(name.length<3) return res.status(400).json({error:'El nombre debe tener al menos 3 caracteres'}); const all=await getAllUsers(); if(all.some(u=>u.id!==user.id && u.username===name)) return res.status(409).json({error:'Ese nombre ya está en uso'}); user.username=name; } if(theme==='dark'||theme==='light') user.theme=theme;   if(profilePic!==undefined) user.profilePic=String(profilePic).slice(0,3_500_000); if(bannerImg!==undefined) user.bannerImg=String(bannerImg).slice(0,8000000); if(chatBg!==undefined) user.chatBg=String(chatBg).slice(0,800_000); await updateUser(user); const lv=levelFromExp(user.exp); res.json({user:publicUser(user),expLevel:lv}); });
app.post('/api/stats', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); ensureShopFields(user); const {seconds=0,exp=0,coins=0}=req.body||{}; user.hoursPlayed=(user.hoursPlayed||0)+(Number(seconds)||0); user.exp=(user.exp||0)+(Number(exp)||0); user.coins=(user.coins||0)+(Number(coins)||0); user.lastSeen=new Date().toISOString(); await updateUser(user); const lv=levelFromExp(user.exp); res.json({user:publicUser(user),expLevel:lv,expGained:Number(exp)||0}); });
app.get('/api/frames',(req,res)=>{ res.json({frames:FRAMES}); });
app.post('/api/frames/buy', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); ensureShopFields(user); const {frameId}=req.body||{}; const frame=FRAMES.find(f=>f.id===frameId); if(!frame) return res.status(404).json({error:'El marco no existe'}); if(user.frames.includes(frameId)) return res.status(400).json({error:'Ya tienes este marco'}); if((user.coins||0)<frame.price) return res.status(400).json({error:'Puntos insuficientes'}); user.coins-=frame.price; user.frames.push(frameId); await updateUser(user); await pushNotification(user.id,'¡Marco comprado! 🖼️',`Desbloqueaste ${frame.name}`,'success'); res.json({coins:user.coins,frames:user.frames}); });
app.post('/api/frames/equip', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); ensureShopFields(user); const {frameId}=req.body||{}; if(!user.frames.includes(frameId)) return res.status(400).json({error:'No tienes este marco'}); user.equippedFrame=frameId; await updateUser(user); res.json({equippedFrame:user.equippedFrame}); });
app.get('/api/name-colors',(req,res)=>{ res.json({colors:NAME_COLORS}); });
app.post('/api/name-colors/buy', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); ensureShopFields(user); const {colorId}=req.body||{}; const col=NAME_COLORS.find(c=>c.id===colorId); if(!col) return res.status(404).json({error:'Color no existe'}); if(user.ownedNameColors.includes(colorId)) return res.status(400).json({error:'Ya tienes este color'}); if((user.exp||0)<col.price) return res.status(400).json({error:`Necesitas ${col.price} EXP (tienes ${user.exp})`}); user.exp-=col.price; user.ownedNameColors.push(colorId); await updateUser(user); await pushNotification(user.id,'¡Color comprado! 🎨',`Desbloqueaste ${col.name}`,'success'); res.json({exp:user.exp, ownedNameColors:user.ownedNameColors}); });
app.post('/api/name-colors/equip', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); ensureShopFields(user); const {colorId}=req.body||{}; if(colorId==='white'){ user.nameColor='#ffffff'; await updateUser(user); return res.json({nameColor:user.nameColor}); } const col=NAME_COLORS.find(c=>c.id===colorId); if(!col) return res.status(404).json({error:'Color no existe'}); if(!user.ownedNameColors.includes(colorId)) return res.status(400).json({error:'No tienes este color'}); user.nameColor=col.color; await updateUser(user); res.json({nameColor:user.nameColor}); });
app.get('/api/banners',(req,res)=>{ res.json({banners:BANNERS}); });
app.post('/api/banners/buy', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); ensureShopFields(user); const {bannerId}=req.body||{}; const b=BANNERS.find(x=>x.id===bannerId); if(!b) return res.status(404).json({error:'Banner no existe'}); if(user.banners.includes(bannerId)) return res.status(400).json({error:'Ya tienes este banner'}); if((user.coins||0)<b.price) return res.status(400).json({error:'Puntos insuficientes'}); user.coins-=b.price; user.banners.push(bannerId); await updateUser(user); await pushNotification(user.id,'Banner comprado!','Desbloqueaste '+b.name,'success'); res.json({coins:user.coins,banners:user.banners}); });
app.post('/api/banners/equip', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); ensureShopFields(user); const {bannerId}=req.body||{}; if(bannerId==='none'){ user.equippedBanner='none'; await updateUser(user); return res.json({equippedBanner:user.equippedBanner}); } const b=BANNERS.find(x=>x.id===bannerId); if(!b) return res.status(404).json({error:'Banner no existe'}); if(!user.banners.includes(bannerId)) return res.status(400).json({error:'No tienes este banner'}); user.equippedBanner=bannerId; await updateUser(user); res.json({equippedBanner:user.equippedBanner}); });

app.get('/api/fonts',(req,res)=>{ res.json({fonts:FONTS}); });
app.post('/api/fonts/buy', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); ensureShopFields(user); const {fontId}=req.body||{}; const f=FONTS.find(x=>x.id===fontId); if(!f) return res.status(404).json({error:'Letra no existe'}); if(user.fonts.includes(fontId)) return res.status(400).json({error:'Ya tienes esta letra'}); if((user.coins||0)<f.price) return res.status(400).json({error:'Puntos insuficientes'}); user.coins-=f.price; user.fonts.push(fontId); await updateUser(user); await pushNotification(user.id,'Letra comprada!','Desbloqueaste '+f.name,'success'); res.json({coins:user.coins,fonts:user.fonts}); });
app.post('/api/fonts/equip', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); ensureShopFields(user); const {fontId}=req.body||{}; if(fontId==='normal'){ user.equippedFont='normal'; await updateUser(user); return res.json({equippedFont:user.equippedFont}); } const f=FONTS.find(x=>x.id===fontId); if(!f) return res.status(404).json({error:'Letra no existe'}); if(!user.fonts.includes(fontId)) return res.status(400).json({error:'No tienes esta letra'}); user.equippedFont=fontId; await updateUser(user); res.json({equippedFont:user.equippedFont}); });

app.get('/api/fxs',(req,res)=>{ res.json({fxs:FXS}); });
app.post('/api/fxs/buy', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); ensureShopFields(user); const {fxId}=req.body||{}; const f=FXS.find(x=>x.id===fxId); if(!f) return res.status(404).json({error:'Efecto no existe'}); if(user.fxs.includes(fxId)) return res.status(400).json({error:'Ya tienes este efecto'}); if((user.coins||0)<f.price) return res.status(400).json({error:'Puntos insuficientes'}); user.coins-=f.price; user.fxs.push(fxId); await updateUser(user); await pushNotification(user.id,'Efecto comprado!','Desbloqueaste '+f.name,'success'); res.json({coins:user.coins,fxs:user.fxs}); });
app.post('/api/fxs/equip', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); ensureShopFields(user); const {fxId}=req.body||{}; if(fxId==='none'){ user.equippedFx='none'; await updateUser(user); return res.json({equippedFx:user.equippedFx}); } const f=FXS.find(x=>x.id===fxId); if(!f) return res.status(404).json({error:'Efecto no existe'}); if(!user.fxs.includes(fxId)) return res.status(400).json({error:'No tienes este efecto'}); user.equippedFx=fxId; await updateUser(user); res.json({equippedFx:user.equippedFx}); });


app.get('/api/levels', async (req,res)=>{ const user=await findUserByToken(req); const solved=user?user.progress.filter(p=>p.solved).map(p=>p.level):[]; res.json({total:LEVELS.length,solved,levels:LEVELS}); });
app.get('/api/chat', async (req,res)=>{ const msgs=await getChat(100); res.json({messages:msgs}); });
app.post('/api/chat', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'Debes iniciar sesión para chatear'}); const {text}=req.body||{}; const t=String(text||'').trim(); if(!t) return res.status(400).json({error:'Mensaje vacío'}); if(t.length>500) return res.status(400).json({error:'Mensaje muy largo (máx 500)'}); const msg={id:crypto.randomUUID(),userId:user.id,username:user.username,text:t.slice(0,500),createdAt:new Date().toISOString()}; await addChat(msg); res.json({message:msg}); });
app.delete('/api/chat/:id', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); const id=req.params.id; if(USE_PG){ const r=await pool.query('SELECT * FROM chat_messages WHERE id=$1',[id]); if(!r.rows[0]) return res.status(404).json({error:'Mensaje no encontrado'}); if(r.rows[0].user_id!==user.id) return res.status(403).json({error:'No puedes borrar mensajes ajenos'}); await pool.query('DELETE FROM chat_messages WHERE id=$1',[id]); } else { const m=(fileDb.chat||[]).find(c=>c.id===id); if(!m) return res.status(404).json({error:'Mensaje no encontrado'}); if(m.userId!==user.id) return res.status(403).json({error:'No puedes borrar mensajes ajenos'}); fileDb.chat=fileDb.chat.filter(c=>c.id!==id); saveDb(fileDb); } res.json({ok:true}); });
/* FRIENDS */
async function getFriendships(userId){
  if(USE_PG){ const r=await pool.query('SELECT * FROM friendships WHERE requester_id=$1 OR addressee_id=$1',[userId]); return r.rows.map(x=>({id:x.id,requesterId:x.requester_id,addresseeId:x.addressee_id,status:x.status,createdAt:x.created_at})); }
  return fileDb.friendships.filter(f=>f.requesterId===userId||f.addresseeId===userId);
}
app.get('/api/friends', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); const frs=await getFriendships(user.id); const users=await getAllUsers(); const map=new Map(users.map(u=>[u.id,u])); const out=frs.map(f=>{ const otherId=f.requesterId===user.id?f.addresseeId:f.requesterId; const other=map.get(otherId); return {id:f.id,otherId,username:other?other.username:'?',profilePic:other?other.profilePic:'',online:other?isOnline(other.lastSeen):false, nameColor:other?other.nameColor:'#ffffff', equippedFont:other?(other.equippedFont||'normal'):'normal', equippedFx:other?(other.equippedFx||'none'):'none', status:f.status, isRequester:f.requesterId===user.id, createdAt:f.createdAt}; }); res.json({friends:out}); });
app.post('/api/friends/request', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); const {username,userId}=req.body||{}; let target=null; if(userId) target=await getUserById(userId); else if(username) target=await getUserByUsername(String(username).trim()); if(!target) return res.status(404).json({error:'Usuario no encontrado'}); if(target.id===user.id) return res.status(400).json({error:'No puedes agregarte a ti mismo'}); const existing=await getFriendships(user.id); if(existing.some(f=> (f.requesterId===user.id&&f.addresseeId===target.id)||(f.requesterId===target.id&&f.addresseeId===user.id)) ) return res.status(400).json({error:'Ya existe solicitud o amistad'}); const fr={id:crypto.randomUUID(),requesterId:user.id,addresseeId:target.id,status:'pending',createdAt:new Date().toISOString()}; if(USE_PG) await pool.query('INSERT INTO friendships(id,requester_id,addressee_id,status,created_at) VALUES($1,$2,$3,$4,$5)',[fr.id,fr.requesterId,fr.addresseeId,fr.status,fr.createdAt]); else { fileDb.friendships.push(fr); saveDb(fileDb); } await pushNotification(target.id,'👥 Solicitud de amistad',`${user.username} te envió solicitud de amistad. Acepta en Amigos.`,`info`); res.json({request:fr}); });
app.post('/api/friends/accept', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); const {requestId}=req.body||{}; let fr=null; if(USE_PG){ const r=await pool.query('SELECT * FROM friendships WHERE id=$1',[requestId]); if(r.rows[0]) fr={id:r.rows[0].id,requesterId:r.rows[0].requester_id,addresseeId:r.rows[0].addressee_id,status:r.rows[0].status,createdAt:r.rows[0].created_at}; } else fr=fileDb.friendships.find(f=>f.id===requestId); if(!fr) return res.status(404).json({error:'Solicitud no encontrada'}); if(fr.addresseeId!==user.id) return res.status(403).json({error:'No autorizado'}); if(fr.status!=='pending') return res.status(400).json({error:'Ya procesada'}); fr.status='accepted'; if(USE_PG) await pool.query('UPDATE friendships SET status=$1 WHERE id=$2',['accepted',fr.id]); else saveDb(fileDb); const requester=await getUserById(fr.requesterId); await pushNotification(fr.requesterId,'✅ Amistad aceptada',`${user.username} aceptó tu solicitud. Ya pueden chatear en privado.`,`success`); res.json({ok:true}); });
app.post('/api/friends/reject', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); const {requestId}=req.body||{}; let fr=null; if(USE_PG){ const r=await pool.query('SELECT * FROM friendships WHERE id=$1',[requestId]); if(r.rows[0]) fr={id:r.rows[0].id,requesterId:r.rows[0].requester_id,addresseeId:r.rows[0].addressee_id,status:r.rows[0].status}; } else fr=fileDb.friendships.find(f=>f.id===requestId); if(!fr) return res.status(404).json({error:'Solicitud no encontrada'}); if(fr.addresseeId!==user.id && fr.requesterId!==user.id) return res.status(403).json({error:'No autorizado'}); if(USE_PG) await pool.query('DELETE FROM friendships WHERE id=$1',[requestId]); else { fileDb.friendships=fileDb.friendships.filter(f=>f.id!==requestId); saveDb(fileDb); } res.json({ok:true}); });
app.delete('/api/friends/:id', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); const id=req.params.id; let fr=null; if(USE_PG){ const r=await pool.query('SELECT * FROM friendships WHERE id=$1',[id]); if(r.rows[0]) fr={id:r.rows[0].id,requesterId:r.rows[0].requester_id,addresseeId:r.rows[0].addressee_id}; } else fr=fileDb.friendships.find(f=>f.id===id); if(!fr) return res.status(404).json({error:'No encontrado'}); if(fr.requesterId!==user.id && fr.addresseeId!==user.id) return res.status(403).json({error:'No autorizado'}); if(USE_PG) await pool.query('DELETE FROM friendships WHERE id=$1',[id]); else { fileDb.friendships=fileDb.friendships.filter(f=>f.id!==id); saveDb(fileDb); } res.json({ok:true}); });
app.get('/api/friends/private/:friendId', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); const friendId=req.params.friendId; const frs=await getFriendships(user.id); const ok=frs.some(f=>f.status==='accepted' && (f.requesterId===friendId || f.addresseeId===friendId)); if(!ok) return res.status(403).json({error:'No son amigos'}); let msgs=[]; if(USE_PG){ const r=await pool.query('SELECT * FROM private_messages WHERE (sender_id=$1 AND receiver_id=$2) OR (sender_id=$2 AND receiver_id=$1) ORDER BY created_at ASC LIMIT 100',[user.id,friendId]); msgs=r.rows.map(x=>({id:x.id,senderId:x.sender_id,receiverId:x.receiver_id,text:x.text,createdAt:x.created_at})); } else msgs=fileDb.privateMessages.filter(m=>(m.senderId===user.id&&m.receiverId===friendId)||(m.senderId===friendId&&m.receiverId===user.id)).sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt)).slice(-100); res.json({messages:msgs}); });
app.post('/api/friends/private/:friendId', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); const friendId=req.params.friendId; const {text}=req.body||{}; const t=String(text||'').trim(); if(!t) return res.status(400).json({error:'Mensaje vacío'}); if(t.length>500) return res.status(400).json({error:'Muy largo'}); const frs=await getFriendships(user.id); const ok=frs.some(f=>f.status==='accepted' && (f.requesterId===friendId || f.addresseeId===friendId)); if(!ok) return res.status(403).json({error:'No son amigos'}); const msg={id:crypto.randomUUID(),senderId:user.id,receiverId:friendId,text:t.slice(0,500),createdAt:new Date().toISOString()}; if(USE_PG) await pool.query('INSERT INTO private_messages(id,sender_id,receiver_id,text,created_at) VALUES($1,$2,$3,$4,$5)',[msg.id,msg.senderId,msg.receiverId,msg.text,msg.createdAt]); else { fileDb.privateMessages.push(msg); if(fileDb.privateMessages.length>2000) fileDb.privateMessages=fileDb.privateMessages.slice(-2000); saveDb(fileDb); } await pushNotification(friendId,'💬 Mensaje privado',`${user.username}: ${t.slice(0,40)}`,`info`); res.json({message:msg}); });
const TOURNAMENT_DURATION_DAYS=15;
function computeEndDate(){ const d=new Date(); d.setDate(d.getDate()+TOURNAMENT_DURATION_DAYS); d.setHours(0,0,0,0); return d; }
async function getActiveTournament(){ const tours=await getTournaments(); return tours.find(t=>t.status==='active')||null; }
async function getPendingTournament(){ const tours=await getTournaments(); return tours.find(t=>t.status==='pending')||null; }
async function startTournament(){ const now=new Date(); const endDate=computeEndDate(); const tournament={id:crypto.randomUUID(),startDate:now.toISOString(),endDate:endDate.toISOString(),status:'active',results:{}}; await createTournament(tournament); return tournament; }
async function endTournament(tournament){ const users=await getAllUsers(); const board=users.map(u=>({id:u.id,username:u.username,solved:u.progress.filter(p=>p.solved).length,attempts:u.progress.reduce((a,p)=>a+p.attempts,0),exp:u.exp||0})).sort((a,b)=>b.solved-a.solved||b.exp-a.exp||a.attempts-b.attempts); board.forEach((entry,i)=>{ tournament.results[entry.id]={position:i+1}; }); for(const entry of board){ const pos=tournament.results[entry.id].position; const user=await getUserById(entry.id); if(!user) continue; ensureShopFields(user); let rewardText=''; if(pos===1){ if(user.frames && !user.frames.includes('campeon')) user.frames.push('campeon'); if(user.skins && !user.skins.includes('tournament_silver')) user.skins.push('tournament_silver'); user.coins=(user.coins||0)+100; rewardText='🏆 ¡Campeón! Marco Campeón Animado + Nave Silver Ranked + 100 puntos'; } else if(pos===2){ if(user.skins && !user.skins.includes('tournament_silver')) user.skins.push('tournament_silver'); user.coins=(user.coins||0)+60; rewardText='🥈 ¡Subcampeón! Nave Silver Ranked + 60 puntos'; } else if(pos===3){ user.coins=(user.coins||0)+60; rewardText='🥉 ¡Tercer puesto! + 60 puntos'; } else { user.coins=(user.coins||0)+40; rewardText=`🎯 Puesto #${pos}. + 40 puntos`; } await updateUser(user); await pushNotification(user.id,'🏆 Torneo RANKED finalizado',`Quedaste en puesto #${pos}. ${rewardText}`,'success'); } tournament.status='finished'; await updateTournament(tournament); }
app.get('/api/tournament', async (req,res)=>{ let tournament=await getActiveTournament(); if(!tournament) tournament=await getPendingTournament(); const users=await getAllUsers(); const playerCount=users.length; res.json({tournament: tournament?{id:tournament.id,status:tournament.status,startDate:tournament.startDate,endDate:tournament.endDate,results:tournament.results}:null, playerCount, minPlayers:10, canStart: playerCount>=10}); });
app.post('/api/tournament/start', async (req,res)=>{ const user=await findUserByToken(req); if(!user) return res.status(401).json({error:'No autenticado'}); if(await getActiveTournament()) return res.status(400).json({error:'Ya hay un torneo activo'}); const users=await getAllUsers(); if(users.length<10) return res.status(400).json({error:`Se necesitan 10 jugadores para empezar`}); const tournament=await startTournament(); res.json({tournament}); });
app.post('/api/tournament/check', async (req,res)=>{ const active=await getActiveTournament(); if(active){ if(new Date(active.endDate)<=new Date()){ await endTournament(active); return res.json({ended:true, tournament:active}); } return res.json({active:true,endDate:active.endDate}); } res.json({active:false}); });

const ADMIN_KEY = process.env.ADMIN_KEY || '';
async function dumpDb(){
  if(USE_PG){
    const users=(await pool.query('SELECT * FROM users')).rows.map(pgRowToUser);
    const sessions=(await pool.query('SELECT * FROM sessions')).rows.map(x=>({token:x.token,userId:x.user_id}));
    const notifications=(await pool.query('SELECT * FROM notifications')).rows.map(x=>({id:x.id,userId:x.user_id,title:x.title,body:x.body,type:x.type,read:x.read,createdAt:x.created_at}));
    const tournaments=(await pool.query('SELECT * FROM tournaments')).rows.map(x=>({id:x.id,status:x.status,startDate:x.start_date,endDate:x.end_date,results:JSON.parse(x.results||'{}')}));
    const chat=(await pool.query('SELECT * FROM chat_messages')).rows.map(x=>({id:x.id,userId:x.user_id,username:x.username,text:x.text,createdAt:x.created_at}));
    const friendships=(await pool.query('SELECT * FROM friendships')).rows.map(x=>({id:x.id,requesterId:x.requester_id,addresseeId:x.addressee_id,status:x.status,createdAt:x.created_at}));
    const privateMessages=(await pool.query('SELECT * FROM private_messages')).rows.map(x=>({id:x.id,senderId:x.sender_id,receiverId:x.receiver_id,text:x.text,createdAt:x.created_at}));
    return {version:1,exportedAt:new Date().toISOString(),users,sessions,notifications,tournaments,chat,friendships,privateMessages};
  }
  return Object.assign({version:1,exportedAt:new Date().toISOString()},JSON.parse(JSON.stringify(fileDb)));
}
async function importDb(d){
  if(!d||!Array.isArray(d.users)) throw new Error('Respaldo invalido');
  if(USE_PG){
    for(const u of d.users){ ensureShopFields(u); await pgUpsertUser(u); }
    for(const s of (d.sessions||[])){ try{ await pool.query('INSERT INTO sessions(token,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[s.token,s.userId]); }catch(e){} }
    for(const n of (d.notifications||[])){ try{ await pool.query('INSERT INTO notifications(id,user_id,title,body,type,read,created_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT DO NOTHING',[n.id,n.userId,n.title,n.body,n.type,n.read,n.createdAt]); }catch(e){} }
    for(const t of (d.tournaments||[])){ try{ await pool.query('INSERT INTO tournaments(id,status,start_date,end_date,results) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING',[t.id,t.status,t.startDate,t.endDate,JSON.stringify(t.results||{})]); }catch(e){} }
    for(const m of (d.chat||[])){ try{ await pool.query('INSERT INTO chat_messages(id,user_id,username,text,created_at) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING',[m.id,m.userId,m.username,m.text,m.createdAt]); }catch(e){} }
    for(const f of (d.friendships||[])){ try{ await pool.query('INSERT INTO friendships(id,requester_id,addressee_id,status,created_at) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING',[f.id,f.requesterId,f.addresseeId,f.status,f.createdAt]); }catch(e){} }
    for(const m of (d.privateMessages||[])){ try{ await pool.query('INSERT INTO private_messages(id,sender_id,receiver_id,text,created_at) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING',[m.id,m.senderId,m.receiverId,m.text,m.createdAt]); }catch(e){} }
  } else {
    const byId=(arr)=>(new Map((arr||[]).map(x=>[x.id,x])));
    const mu=byId(fileDb.users); (d.users||[]).forEach(u=>{ ensureShopFields(u); mu.set(u.id,u); }); fileDb.users=[...mu.values()];
    const ms=byId(fileDb.sessions); (d.sessions||[]).forEach(s=>ms.set(s.token||s.id,s)); fileDb.sessions=[...ms.values()];
    const mn=byId(fileDb.notifications); (d.notifications||[]).forEach(n=>mn.set(n.id,n)); fileDb.notifications=[...mn.values()];
    const mt=byId(fileDb.tournaments); (d.tournaments||[]).forEach(x=>mt.set(x.id,x)); fileDb.tournaments=[...mt.values()];
    const mc=byId(fileDb.chat); (d.chat||[]).forEach(m=>mc.set(m.id,m)); fileDb.chat=[...mc.values()];
    const mf=byId(fileDb.friendships); (d.friendships||[]).forEach(f=>mf.set(f.id,f)); fileDb.friendships=[...mf.values()];
    const mp=byId(fileDb.privateMessages); (d.privateMessages||[]).forEach(m=>mp.set(m.id,m)); fileDb.privateMessages=[...mp.values()];
    saveDb(fileDb);
  }
  return {users:(d.users||[]).length};
}
app.post('/api/admin/export', async (req,res)=>{ const {key}=req.body||{}; if(!ADMIN_KEY||key!==ADMIN_KEY) return res.status(403).json({error:'Clave de admin incorrecta o no configurada'}); try{ const dump=await dumpDb(); res.json({dump}); }catch(e){ res.status(500).json({error:'No se pudo exportar'}); } });
app.post('/api/admin/import', async (req,res)=>{ const {key,dump}=req.body||{}; if(!ADMIN_KEY||key!==ADMIN_KEY) return res.status(403).json({error:'Clave de admin incorrecta o no configurada'}); try{ const r=await importDb(dump); res.json({ok:true,users:r.users}); }catch(e){ res.status(400).json({error:e.message||'Respaldo invalido'}); } });

app.get('/api/status', async (req,res)=>{ try{ const users=await getAllUsers(); res.json({storage:USE_PG?'postgres':'json-temporal',users:users.length,time:new Date().toISOString()}); }catch(e){ res.status(500).json({error:'status error'}); } });
(async()=>{ await initPg(); try{ const _u=await getUserByUsername('gusguslu'); if(_u){ const _t=17470; if(_u.speedrunBest==null || _t < _u.speedrunBest){ _u.speedrunBest=_t; if(!_u.speedrunHistory) _u.speedrunHistory=[]; if(!_u.speedrunHistory.some(h=>h.time===_t)) _u.speedrunHistory.push({time:_t,at:new Date().toISOString()}); await updateUser(_u); console.log(`[fix] gusguslu speedrun ${_t}ms set`);} } }catch(e){ console.log('fix gusguslu',e.message); } try{ const _p=await getUserByUsername('piza'); if(_p){ const _t2=17140; if(_p.speedrunBest==null || _t2 < _p.speedrunBest){ _p.speedrunBest=_t2; if(!_p.speedrunHistory) _p.speedrunHistory=[]; if(!_p.speedrunHistory.some(h=>h.time===_t2)) _p.speedrunHistory.push({time:_t2,at:new Date().toISOString()}); await updateUser(_p); console.log(`[fix] piza speedrun ${_t2}ms set`);} } }catch(e){ console.log('fix piza',e.message); } app.listen(PORT,()=>{ console.log(`👾 Code Invaders corriendo en http://localhost:${PORT} ${USE_PG?'[PG]':'[JSON]'}`); }); })();
